/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeeDataBase;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author KFelt
 */
public class Main {
    public static ArrayList<EMPLOYEE> employees = new ArrayList<>();
    public static Scanner sc = new Scanner(System.in);

    public static void main(String[] args) throws  IOException, InterruptedException{
        employees = ReadData.readData(employees);
        while(true){
            int userSelection = MainMenu.mainMenu();
            switch(userSelection){
                case 1:
                    CreateEmployee.createEmployee(employees);
                    break;
                case 2:
                    ModifyEmployeeData.modifyEmployeeData(employees);
                    break;               
                case 3:
                    RemoveEmployee.removeEmployee(employees);
                    break;
                case 4:
                    DisplayEmployees.displayEmployees(employees);
                    break;
                case 5:
                    SaveEmployeeList.saveEmployeeList(employees);
                    break;
                case 0:
                    sc.close();
                    System.exit(0);
            }
        }
    }
}